##What is Numpy?


*   The numerical python library used for working with arrays.
*   Created in 2005 by Travis Oliphant
*   Written partially in Python, but most of the parts that require fast computation are written in C or C++.





. 






##Why use Numpy?
*   Has functions for working in domain of linear algebra, fourier transform, and matrices.
*   Aims to provide an array object that is up to 50x times faster than traditional Python lists.
*   Forms the foundation of Machine Learning Stack


### Import Numpy
Numpy package is imported as alias **np**

In [ ]:
import numpy as np
# The list type data type which we work with in numpy is called n-dim array. 

## Creating an 1-D Array(Vector)


In [ ]:
# There are many ways to create a Vector. The first one is with use of python list.

#Row Vector
list_row = [2,6,4,8,2,1,4,3]
array_row = np.array(list_row)
print(array_row)
print('Shape of Matrix is',array_row.shape)

[2 6 4 8 2 1 4 3]
Shape of Matrix is (8,)


In [ ]:
#Column Vector
list_col =[[2],[6],[4],[8],[2],[1],[4],[3]]
array_col = np.array(list_col)
print(array_col)
print('Shape of Matrix is',array_col.shape)

[[2]
 [6]
 [4]
 [8]
 [2]
 [1]
 [4]
 [3]]
Shape of Matrix is (8, 1)


## Creating a 2D array (Matrix)

In [ ]:

# Similiarly, Matrix is formed using list of list.
list_mat = [[2,6,4],[8,2,1],[1,4,3]] 

array_mat = np.array(list_mat)

print(array_mat)
# Printing type of arr object
print("Array is of type: ", type(array_mat))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", array_mat.ndim)
 
# Printing shape of array
print("Shape of array: ", array_mat.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", array_mat.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", array_mat.dtype)

[[2 6 4]
 [8 2 1]
 [1 4 3]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9
Array stores elements of type:  int64


**The elements of an array are originally unknown, but it's size is known. Hence, Numpy offers several functions to create arrays with initial placeholder content.**

In [ ]:


#returns a new array of specified size filled with zeros
x_default = np.zeros((2, 2))

# x_datatype_specified = np.zeros((2, 2), dtype=int)

print (x_default)
# print(x_datatype_specified)

[[0. 0.]
 [0. 0.]]


In [ ]:


#returns a new array of specified size filled with ones
x_default = np.ones((2, 2))

# x_datatype_specified = np.ones((2, 2), dtype=int)

print (x_default)
# print(x_datatype_specified)

[[1. 1.]
 [1. 1.]]


In [ ]:


#returns a new array of specified size filled with random values
x_default = np.empty((2, 3))

# x_datatype_specified = np.empty((2, 3), dtype=int)

print (x_default)
# print(x_datatype_specified)

[[2.31401614e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


**Here we will see how to create an array from numerical ranges**

In [ ]:

x = np.arange(5)
print (x)


[0 1 2 3 4]


In [ ]:
# start and stop parameters set
import numpy as np
x = np.arange(10,20,2)
print (x)


[10 12 14 16 18]


In [ ]:
import numpy as np
# function linspace that receives as an argument the number of elements that we want, instead of the step:
x = np.linspace(0, 2, 9)

print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### Array Indexing
Knowing the basics of array indexing is important for analysing and manipulating the array object.
* Slicing
* Integer array indexing
* Boolean array indexing

In [ ]:
#Here we will discuss only slicing
x = np.arange(10, 28, 2).reshape(3,3)

print(x)
#We will the perform slicing on the given array now

y = x[:, 2]
y = x[2, :]
y = x[:2, :2]
y = x[2:, 2:]
print(y)

[[10 12 14]
 [16 18 20]
 [22 24 26]]
[[26]]


In [ ]:
x  = np.arange(120, 138, 2)
print(x)

y = x.reshape(3, 3)
print('Reshaped the matrix into a 3*3 matrix: ')
print(y)

[120 122 124 126 128 130 132 134 136]
Reshaped the matrix into a 3*3 matrix: 
[[120 122 124]
 [126 128 130]
 [132 134 136]]
