In [1]:
#Q NO 1
import numpy as np

In [2]:
#Q NO 2
row_list= [0,1,2,3,4,5,6,7,8,9]
row_vector = np.array(row_list)
print(row_vector)
print(row_vector.shape)
print(row_vector.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [3]:
#Q NO 3
matrix = np.arange(24).reshape(4,6)
print(matrix)
print(matrix.shape)
print(matrix.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [4]:
#Q no 4
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#Q NO 5
np.zeros((3,2),dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
#Q NO 6
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
#Q NO 7
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#Q NO 8
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
# Q NO 9
np.linspace(1,5,20).reshape(4,5)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [10]:
#Q NO 10
np.random.rand(10)

array([0.94871473, 0.54849638, 0.47637295, 0.78323215, 0.99190915,
       0.85348565, 0.45709666, 0.70003474, 0.53402116, 0.96365624])

In [11]:
#Q NO 11
np.random.randn(3,6)

array([[ 1.45390118, -0.82913606,  0.7664135 , -1.8288663 , -0.01097996,
         1.36792672],
       [ 0.04289405,  0.55429813, -1.33062211,  1.25036349, -1.20316948,
        -0.12634273],
       [-0.19122278,  2.21631063,  0.18494343,  1.62820277,  0.57199323,
         0.0599625 ]])

In [12]:
#Q NO 12
np.random.randint(5,9,12).reshape(3,4)

array([[5, 6, 6, 7],
       [8, 7, 6, 6],
       [6, 8, 8, 5]])

In [13]:
#Q NO 13
v =[17, 32, 26, 23, 8, 8, 17, 14, 26, 14, 23, 20, 32, 8, 26]
v = np.array(v) 
print(v[0],v[4],v[-6],v[-3],v[-1])   

17 8 14 32 26


In [14]:
#Q NO 14
print(v[:])
print(v[0:])
print(v[1:-1])
print(v[-4:])
print(v[-5:-2])

[17 32 26 23  8  8 17 14 26 14 23 20 32  8 26]
[17 32 26 23  8  8 17 14 26 14 23 20 32  8 26]
[32 26 23  8  8 17 14 26 14 23 20 32  8]
[20 32  8 26]
[23 20 32]


In [24]:
#Q NO 15
mat = np.random.randint(1,100,(6,7))
print(mat)
print(mat[0][-1])
print(mat[-1][-1])
print(mat[1][4])
print(mat[-3][-4])

[[42 24 23 94  1 37 86]
 [15 69 83 30 92 85 12]
 [68 48 37 82 29 49 98]
 [22 83 44 28 77  4 91]
 [37 42 42 56  3 52 35]
 [54 65 62 91 34 63 68]]
86
68
92
28


In [26]:
#Q NO 16
print(mat[2,:])
print(mat[:,4])
print(mat[:3,2:])
print(mat[-2,-3:-1])

[68 48 37 82 29 49 98]
[ 1 92 29 77  3 34]
[[23 94  1 37 86]
 [83 30 92 85 12]
 [37 82 29 49 98]]
[ 3 52]


In [17]:
#Q NO 17
copy_v = np.copy(v)
copy_v[4:] = 0
print(copy_v)
print(v)

[17 32 26 23  0  0  0  0  0  0  0  0  0  0  0]
[17 32 26 23  8  8 17 14 26 14 23 20 32  8 26]


In [18]:
# Q NO 18

a= [3,4]
b=[5,12]

#Creating Array
arr_a = np.array(a)
arr_b = np.array(b)

#Finding Magnitude
mag_a = np.linalg.norm(arr_a)
mag_b = np.linalg.norm(arr_b)
print('Magnitude of a &b are:',mag_a ,'and', mag_b )

#Dot Product
dot_product = np.dot(arr_a,arr_b)
print('Dot product of a & b is: ',dot_product)

#Cross Product
cross_product = np.cross(arr_a,arr_b)
print('Cross product of a & b is: ',cross_product)

#Cos Angle
cos = dot_product / (mag_a * mag_b)
cos_rad = np.arccos(cos)
cos_degree = (cos_rad * 180) / np.pi
print('Cos Angle is',cos_degree)

#Sine Angle
sine = cross_product / (mag_a * mag_b)
sine_rad = np.arcsin(sine)
sine_degree = (sine_rad * 180) / np.pi
print('Sine Angle is',sine_degree)


Magnitude of a &b are: 5.0 and 13.0
Dot product of a & b is:  63
Cross product of a & b is:  16
Cos Angle is 14.250032697803595
Sine Angle is 14.250032697803595


In [19]:
#Q NO 19
sqr_mat = np.random.randint(9,21,9).reshape(3,3)
print(sqr_mat)

[[18 17 12]
 [19 19 16]
 [15 14 13]]


In [20]:
#Q NO 20

inv = np.linalg.inv(sqr_mat)
diag_elems = np.diag(sqr_mat)

print('Diagonal Elements are: ',diag_elems)
print('Inverse Matrix is: ',inv)


Diagonal Elements are:  [18 19 13]
Inverse Matrix is:  [[ 0.34328358 -0.79104478  0.65671642]
 [-0.10447761  0.80597015 -0.89552239]
 [-0.28358209  0.04477612  0.28358209]]


In [21]:
#Q NO 21
np.diag([1,4,3])

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])